// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"go-users/entities"
	"gorm.io/gorm"
)

type User struct {
	gorm.Model
	Name   string
	Email  string
	Status entities.UserStatus
}
