version: "3.9"
services:
  web:
    image: dcoer-go-web:v1
    ports:
      - "8081:8081"
    volumes:
      - ./logs:/usr/src/app/logs 
      - ./cfg:/usr/src/app/cfg           
    links:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6377:6379"
